
```{r eval=FALSE}

# conda activate cicero
library(Seurat)
library(tidyverse)
library(cowplot)
library(viridis)
library(ggpubr)
library(ggrepel)
library(patchwork)
library(RColorBrewer)
theme_set(theme_cowplot())

setwd( "/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/")
data_dir <- 'data/'
fig_dir <- 'figures/'

# load initial seurat object
seurat_obj <- readRDS('/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/initial_seurat.rds')

```

Save counts matrix etc so I can run scrublet to locate the doublets

```{r eval=FALSE}

# save counts matrix and meta data so we can load into scanpy to use scrublet:

X <- GetAssayData(seurat_obj, assay='RNA', slot='counts')
Matrix::writeMM(X, file="/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/NucSeq_final_counts.mtx")

seurat_obj$barcode <- colnames(seurat_obj)
meta <- seurat_obj@meta.data
write.csv(meta, file="/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/NucSeq_final_meta.csv", quote=FALSE)

gene_names <- rownames(seurat_obj)
write.table(gene_names, file="/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/NucSeq_final_gene_names.csv", quote=FALSE, row.names=FALSE, col.names=FALSE, sep=',')

```

scrublet

```{python}

import scanpy as sc
import scrublet as scr
import numpy as np
from matplotlib import pyplot as plt
import argparse
import os
from scipy import io
from scipy.sparse import coo_matrix, csr_matrix
import pandas as pd
import anndata
sc.settings.set_figure_params(dpi=500, dpi_save=1000, figsize=(5,5), facecolor='white')

# load sparse matrix:
X = io.mmread("/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/NucSeq_final_counts.mtx")

# create anndata object
adata = anndata.AnnData(
    X=X.transpose().tocsr()
)

# load sample metadata:
sample_meta = pd.read_csv("/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/NucSeq_final_meta.csv")

# load gene names:
with open("/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/NucSeq_final_gene_names.csv", 'r') as f:
    gene_names = f.read().splitlines()


adata.obs = sample_meta
adata.obs.index = adata.obs['barcode']
adata.obs = adata.obs.drop(labels='barcode', axis=1)
adata.var.index = gene_names

# compute doublets for each sample:
meta_list = []
for sample in adata.obs['Sample.ID'].unique():
    print(sample)
    cur_adata = adata[adata.obs['Sample.ID'] == sample]

    scrub = scr.Scrublet(cur_adata.X)
    cur_adata.obs['doublet_scores'], predicted_doublets = scrub.scrub_doublets()
    cur_adata.obs['doublets'] = np.where(predicted_doublets== False, 'Singlet', 'Doublet')
    print(cur_adata.obs.doublets.value_counts())
    print()
    meta_list.append(cur_adata.obs)

# combine the doublet metadata
meta = pd.concat(meta_list)
meta = meta[['doublet_scores', 'doublets']]

doublet_df = pd.merge(adata.obs, meta, left_index=True, right_index=True)
doublet_df = doublet_df[['doublet_scores', 'doublets']]
doublet_df.to_csv("/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/NucSeq_final_doublets.csv")

```

Plot the doublets in Seurat

```{r eval=FALSE}

# load the doublet table into R and add to seurat object:
doublet_df <- read.csv("/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/NucSeq_final_doublets.csv")

seurat_obj$doublet_scores <- doublet_df$doublet_scores
seurat_obj$doublets <- doublet_df$doublets

# plot the doublet scores
p1 <- FeaturePlot(seurat_obj, features='doublet_scores', raster=FALSE, order=TRUE) + umap_theme +
  scale_color_gradientn(colors=magma(256))

p2 <- DimPlot(seurat_obj, cells.highlight=colnames(seurat_obj)[seurat_obj$doublets=='Doublet']) + umap_theme + NoLegend() + ggtitle('predicted doublets') + theme(plot.title=element_text(hjust=0.5))

p3 <- DimPlot(seurat_obj, group.by='cell_type', label=TRUE, raster=FALSE) + umap_theme + NoLegend()

pdf(paste0(fig_dir, 'umap_doublets.pdf'), width=15, height=5)
p1 | p2 | p3
dev.off()

# remove the cells predicted as doublets
seurat_obj <- subset(seurat_obj, doublets=='Singlet')
seurat_obj <- subset(seurat_obj, cell_type != 'Doublet')

```

Integration with liger

```{r eval=FALSE}

library(rliger)

exp_mat <- GetAssayData(seurat_obj, slot='counts')
expression_list <- list(
  '1' = exp_mat[,rownames(seurat_obj@meta.data %>% subset(snRNAseq.Batch == '1'))],
  '2' = exp_mat[,rownames(seurat_obj@meta.data %>% subset(snRNAseq.Batch == '2'))]
)


liger_obj <- createLiger(expression_list)
liger_obj <- normalize(liger_obj)

# find variable genes in each dataset
pdf(paste0(fig_dir, 'liger_variableGenes.pdf'), width=8, height=8)
liger_obj <- selectGenes(
  liger_obj,
  var.thresh =c(0.2,0.225),
  do.plot=T
)
dev.off()
liger_obj <- scaleNotCenter(liger_obj)

# run online iNMF
liger_obj = online_iNMF(liger_obj, k=30, max.epochs=5)

# quantile normalization
liger_obj  = quantile_norm(liger_obj)
liger_obj  = runUMAP(liger_obj)

pdf('figures/liger_umap.pdf', width=8, height=8)
plotByDatasetAndCluster(liger_obj, axis.labels = c("UMAP1","UMAP2"))
dev.off()

saveRDS(liger_obj, file="/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/NucSeq_final_doublets_removed_online_inmf.rds")
liger_obj <- readRDS("/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/NucSeq_final_doublets_removed_online_inmf.rds")

# transfer iNMF matrix to seurat obj:
seurat_obj@reductions$online_iNMF <- CreateDimReducObject(
    loadings=t(liger_obj@W),
    embeddings=liger_obj@H.norm[colnames(seurat_obj),],
    key="onlineiNMF_",
    assay="RNA"
  )


seurat_obj <- RunUMAP(seurat_obj, reduction='online_iNMF', dims = 1:30, n.neighbors=15, min.dist=0.10)
seurat_obj <- FindNeighbors(seurat_obj, dims=1:30, reduction='online_iNMF', annoy.metric='cosine')
seurat_obj <- FindClusters(seurat_obj, resolution = 0.5)


# save so we can run parallel marker genes:
saveRDS(seurat_obj, file="/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/NucSeq_final_doublets_removed_online_inmf_seurat.rds")


```

Plot canonical cell type markers:

```{r eval=FALSE}


canonical_markers <- list(
  'Astro' = c('Gfap', 'Aqp4', 'Slc1a2', 'Gria1'),
  'Pan-neuron' = c('Snap25', 'Syt1', 'Chat'),
  'Excitatory' = c('Slc17a7', 'Satb2'),
  'Inhibitory' = c('Gad1', 'Gad2'),
  'Microglia' = c('Csf1r', 'Cd74', 'P2ry12'),
  'Oligo' = c('Mobp', 'Mbp', 'Mog'),
  'Imm-Olig' = c('Itpr2', 'Apoe', 'Plp1', 'Tcf7l2'),
  'OPC' = c('Pdgfra', 'Cspg4'),
  'Vascular' = c('Pdgfrb', 'Flt1', 'Kdr', 'Abcc9'),
  'Ependymal' = c('Dnah11'),
  'VLMC' = c('Vtn', 'Lum', 'Col1a2')
)

colfunc <- colorRampPalette(c(rev(brewer.pal(9, 'Purples' )[2:9]), 'white'))

p <- DotPlot(seurat_obj, features=canonical_markers, group.by='seurat_clusters', dot.min=0.15 ) +
  RotatedAxis() +
    scale_color_gradientn( name='Prediction Score',
    colors=rev(colfunc(256)),
    guide = guide_colorbar(barwidth=0.5, barheight=20, ticks=FALSE, label=FALSE)
) +
  ylab('') + xlab('')
pdf(paste0(fig_dir, 'marker_gene_dotplot.pdf'), width=12, height=10, useDingbats=FALSE)
p
dev.off()


```


Get major cell types based on the marker genes:

```{r eval=FALSE}

celltype_df <- read.csv("/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/data/celltype_annotation.csv", stringsAsFactors=FALSE)
seurat_obj$cell_type <- celltype_df$celltype[match(seurat_obj$seurat_clusters, celltype_df$cluster)]
seurat_obj$cluster_name <- celltype_df$cluster_name[match(seurat_obj$seurat_clusters, celltype_df$cluster)]

p1 <- DimPlot(seurat_obj, group.by='cell_type', label=TRUE, raster=FALSE) + umap_theme + NoLegend()
p2 <- DimPlot(seurat_obj, group.by='seurat_clusters', label=TRUE, raster=FALSE) + umap_theme + NoLegend()
p3 <- DimPlot(seurat_obj, group.by='cluster_name', label=TRUE, raster=FALSE) + umap_theme + NoLegend()

pdf(paste0(fig_dir, 'umap_annotated_celltypes.pdf'), width=12, height=4)
p1 | p2 | p3
dev.off()


saveRDS(seurat_obj, file="/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/snRNA_processed_seruat.rds")


```
