
```{r eval=FALSE}

library(Seurat)
library(Signac)
library(tidyverse)
library(RColorBrewer)
library(viridis)
library(cowplot)
library(monocle3)
library(SeuratWrappers)
theme_set(theme_cowplot())

setwd("/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/ATAC")
data_dir <- 'data/'
fig_dir <- 'figures/'

# load atac data
seurat_atac <- readRDS(paste0(data_dir, 'snATAC_processed_seurat.rds'))
DefaultAssay(seurat_atac) <- 'peaks'
seurat_rna <- readRDS("/dfs3b/swaruplab/smorabit/collab/AMRF/analysis/snRNAseq/NucSeq_final_doublets_removed_online_inmf_seurat.rds")

coembed <- readRDS(paste0(data_dir, 'coembed_in_progress.rds'))

# add cell-type annotations for ATAC into the coembed object:
coembed$test <- seurat_atac$subcluster_name[match(colnames(coembed), colnames(seurat_atac))]

# make a col for combined clusters
coembed$Combined.Clusters <- ifelse(
  coembed$tech == 'rna',
  paste0(as.character(coembed$subcluster_name), '_rna'),
  paste0(as.character(coembed$test), '_atac')
)

coembed$batch_integrated <- ifelse(
  coembed$tech == 'atac',
  paste0(coembed$Batch, '_atac'),
  paste0(coembed$snRNAseq.Batch, '_rna')
)

coembed$Time.point <- c(seurat_rna$Time.point, seurat_atac$Timepoint)
coembed$Time.point <- ifelse(
  coembed$tech == 'rna', as.character(coembed$Time.point), as.character(coembed$Timepoint)
)

coembed$Time.point <- factor(
  coembed$Time.point, levels=c('Naive', 'Day.5', 'Day.14', 'Day.30')
)


p <- DimPlot(coembed, group.by='Combined.Clusters', split.by='tech', label=TRUE, raster=FALSE) + umap_theme + NoLegend()
pdf(paste0(fig_dir, 'umap_coembed_split.pdf'), width=10, height=5, useDingbats=FALSE)
p
dev.off()

all.equal(rownames(seurat_atac@meta.data), rownames(coembed@meta.data %>% subset(tech == 'atac')))


```

re-load cell-type-specific data:

```{r eval=FALSE}

cur_celltype <- 'ODC'
seurat_subset <- readRDS(paste0(data_dir, cur_celltype, '_coembed_seurat.rds'))
atac.cds <- readRDS(paste0(data_dir, cur_celltype, '_coembed_cds.rds'))

```

Try Monocle3 on UMAP

Similar code for each cell type just because some setting are slightly different

```{r eval=FALSE}

source('/dfs3b/swaruplab/smorabit/pipelines/sn-rna-seq/bin/sc_utilities.R')

################################################################################
# ASC
################################################################################

cur_celltype <- 'ASC'
fig_dir <- paste0('figures/', cur_celltype, '/'); dir.create(fig_dir)
seurat_subset <- coembed[,colnames(coembed)[grepl(cur_celltype, coembed$Combined.Clusters)]]
DefaultAssay(seurat_subset) <- 'RNA'

# process the CDS
atac.cds <- as.cell_data_set(seurat_subset)
# atac.cds <- reduce_dimension(atac.cds, umap.n_neighbors=25L, umap.min_dist=0.15)
atac.cds <- cluster_cells(cds=atac.cds, reduction_method='UMAP')
atac.cds <- learn_graph(atac.cds, use_partition=TRUE)
principal_node <- get_earliest_principal_node(atac.cds,partition = 1)
atac.cds <- order_cells(atac.cds,root_pr_nodes = principal_node)

pData(atac.cds)$pseudotime <- pseudotime(atac.cds)

# remove cells that are not in partition 1
atac.cds <- atac.cds[,partitions(atac.cds) == 1]
seurat_subset <- seurat_subset[,colnames(atac.cds)]


################################################################################
# MG
################################################################################

cur_celltype <- 'MG'
seurat_subset <- coembed[,colnames(coembed)[grepl(cur_celltype, coembed$Combined.Clusters)]]
DefaultAssay(seurat_subset) <- 'RNA'

################################################################################
# ODCs
################################################################################

cur_celltype <- 'ODC'
fig_dir <- paste0('figures/', cur_celltype); dir.create(fig_dir)
subset.cells <- as.logical(grepl('ODC', coembed$Combined.Clusters) + grepl('OPC', coembed$Combined.Clusters) + grepl('NFOL', coembed$Combined.Clusters) )
# seurat_subset <- coembed[,colnames(coembed)[grepl(cur_celltype, coembed$Combined.Clusters)]]
seurat_subset <- coembed[,colnames(coembed)[subset.cells]]
DefaultAssay(seurat_subset) <- 'RNA'


# process the CDS
atac.cds <- as.cell_data_set(seurat_subset)
# atac.cds <- reduce_dimension(atac.cds, umap.n_neighbors=20L, umap.min_dist=0.15)
atac.cds <- cluster_cells(cds=atac.cds, reduction_method='UMAP')

# remove clusters 26 & 27 as outliers, then cluster again:
atac.cds <- atac.cds[,!(clusters(atac.cds) %in% c(26,27))]
atac.cds <- cluster_cells(cds=atac.cds, reduction_method='UMAP')

# learn graph for pseudotime
atac.cds <- learn_graph(atac.cds, use_partition=TRUE)

# get principal node & order cells
principal_node <- get_earliest_principal_node(atac.cds,partition = 1)
atac.cds <- order_cells(atac.cds,root_pr_nodes = principal_node)

# reverse pseudotime
pData(atac.cds)$Pseudotime <- pseudotime(atac.cds)
pData(atac.cds)$Pseudotime <- (pData(atac.cds)$Pseudotime - max(pData(atac.cds)$Pseudotime)) * -1

#
#
# # partition 1 pseudotime
# #principal_node <- get_earliest_principal_node(atac.cds,partition = 1)
# #atac.cds <- order_cells(atac.cds,root_pr_nodes = principal_node)
# atac.cds <- order_cells(atac.cds, root_cells =colnames(atac.cds)[clusters(atac.cds) == 6][1:100])
# pData(atac.cds)$pseudotime_partition1 <- pseudotime(atac.cds)
#
# # partition 2 pseudotime
# principal_node <- get_earliest_principal_node(atac.cds,partition = 2)
# atac.cds <- order_cells(atac.cds,root_pr_nodes = principal_node)
# pData(atac.cds)$pseudotime_partition2 <- pseudotime(atac.cds)
#
# # merged pseudotime:
# pseudotime_offset <- max(pData(atac.cds)$pseudotime_partition2[is.finite(pData(atac.cds)$pseudotime_partition2)])
#
# test <- ifelse(
#   is.finite(pData(atac.cds)$pseudotime_partition2),
#   pData(atac.cds)$pseudotime_partition2,
#   pData(atac.cds)$pseudotime_partition1 + pseudotime_offset
# )

# pData(atac.cds)$seudotime = test
# pData(atac.cds)$partition <- partitions(atac.cds)

################################################################################
# continue
################################################################################

p <- plot_cells(
  cds = atac.cds,
  color_cells_by = "cluster",
  show_trajectory_graph = FALSE
)

p2 <- plot_cells(
  cds = atac.cds,
  color_cells_by = "Combined.Clusters",
  show_trajectory_graph = FALSE
)


p3 <- plot_cells(
  cds = atac.cds,
  color_cells_by = "Pseudotime",
  show_trajectory_graph = FALSE
)

p4 <- DimPlot(seurat_subset, group.by='Time.point')


pdf(paste0(fig_dir, cur_celltype, '_monocle_coembed.pdf'), width=8, height=8, useDingbats=FALSE)
p + p2 + p3 + p4

dev.off()

p <- DimPlot(coembed, group.by="Cell.Type", split.by="Group.Time", ncol=2, raster=FALSE)

pdf(paste0(fig_dir, cur_celltype, '_test.pdf'), width=8, height=8, useDingbats=FALSE)
p
dev.off()

# save CDS object
saveRDS(atac.cds, paste0(data_dir, cur_celltype, '_coembed_cds.rds'))

# move monocle UMAP to the Seurat object (don't need to do this since I am using the same UMAP)
# umap_df <- reducedDims(atac.cds)$UMAP %>% as.matrix
# rownames(umap_df) <- colnames(seurat_subset)
# colnames(umap_df) <- c('monocleUMAP_1', 'monocleUMAP_2')
#
# seurat_subset@reductions$monocle_umap <- CreateDimReducObject(
#     embeddings=umap_df,
#     assay="RNA"
# )

# add column for monocle pseudotime, clusters, and partitions:

# remove small outlier clusters from seurat obj
seurat_subset <- seurat_subset[,colnames(atac.cds)]

seurat_subset$pseudotime <- atac.cds$Pseudotime
seurat_subset$monocle_clusters <- clusters(atac.cds)
seurat_subset$monocle_partitions <- partitions(atac.cds)

# cut pseudotime trajectory into 10, 50, 100 bins:
valid_pseudotime <- seurat_subset@meta.data %>% subset(pseudotime != Inf)

bins_10 <- valid_pseudotime %>% .$pseudotime %>% Hmisc::cut2(g=10)
bins_50 <- valid_pseudotime %>% .$pseudotime %>% Hmisc::cut2(g=50)
bins_100 <- valid_pseudotime %>% .$pseudotime %>% Hmisc::cut2(g=100)

seurat_subset$pseudotime_bins_10 <- bins_10[match(colnames(seurat_subset), rownames(valid_pseudotime))]
seurat_subset$pseudotime_bins_50 <- bins_50[match(colnames(seurat_subset), rownames(valid_pseudotime))]
seurat_subset$pseudotime_bins_100 <- bins_100[match(colnames(seurat_subset), rownames(valid_pseudotime))]

# save Seurat object
saveRDS(seurat_subset, paste0(data_dir, cur_celltype, '_coembed_seurat.rds'))



p1 <- DimPlot(seurat_subset, split.by='tech', group.by='Combined.Clusters', label=TRUE) + NoLegend() + umap_theme

p2 <- FeaturePlot(seurat_subset, features='pseudotime') +
scale_color_gradientn(colors=plasma(256)) +  umap_theme

p3 <- DimPlot(seurat_subset,  group.by='monocle_clusters', label=TRUE) + NoLegend() + umap_theme

p4 <- DimPlot(seurat_subset, split.by='tech', group.by='batch_integrated', label=TRUE) + NoLegend() + umap_theme


pdf(paste0(fig_dir, cur_celltype, '_monocle_coembed_seurat.pdf'), width=10, height=5, useDingbats=FALSE)
p1
p2 | p3
p4
dev.off()


p1 <- DimPlot(seurat_subset, group.by='pseudotime_bins_10', label=FALSE, cols=plasma(10)) + NoLegend() + umap_theme

p2 <- DimPlot(seurat_subset, group.by='pseudotime_bins_50', label=FALSE, cols=plasma(50)) + NoLegend() + umap_theme

p3 <- DimPlot(seurat_subset, group.by='pseudotime_bins_100', label=FALSE, cols=plasma(100)) + NoLegend() + umap_theme

pdf(paste0(fig_dir, cur_celltype, '_monocle_coembed_seurat_bins.pdf'), width=12, height=4, useDingbats=FALSE)
p1 + p2 + p3
dev.off()

```
